Revert "msm: kgsl: Avoid turning on GPU clock if already off"
This reverts commit 775d1db534b331d5353a46e288456c5619f673b7.

Fixes compilaion error:
drivers/gpu/msm/kgsl_pwrctrl.c:1309:6: error: redefinition of 'kgsl_pwrctrl_isenabled'
drivers/gpu/msm/kgsl_pwrctrl.c:1089:6: note: previous definition of 'kgsl_pwrctrl_isenabled' was here